### ISSUE TITLE
Installation instructions, revisited

### ISSUE THREAD

**Issue by robot-army** [dlharmon/pyopenems#3]
1) Installed fresh Debian 10 (admittedly, in virtualbox...)
2) git submodule init; git submodule update --recursive
3) sudo apt-get install cython3
4) pick up your current instructions
5) Clone your git repo...

Now, no errors, but if I try to run an example: 
"ModuleNotFoundError: No module named 'openems'"...

Feeling like I should stick to swinging hammers...!

**Comment by robot-army** [comment]
[pyopenems_install_fail.txt](https://github.com/dlharmon/pyopenems/files/3444702/pyopenems_install_fail.txt)

I've attached my whole terminal output, except the output from sudo apt build-dep openems which seemed to work.

**Comment by DrYerzinia** [comment]
This one confused me for a bit as well.  The Metal object is in __init__.py in this repo.  So this repo IS the openems import.  Its a big confusing because there is no setup.py etc.
I just made a copy of the repo inside the examples folder and named it openems.  Then you can run the examples.  I'm still working through some issues but wilkinson_1.py ran for me.

**Comment by dlharmon** [comment]
I got a new machine today and decided to try getting this going first so I'd catch any missing packages.

I've updated the installation instructions with more packages and also added a symlink from the examples folder to the top level so they will run without setting up the python path. I also added a note about the python path.

Sorry it took me so long to get to this.

Commit 4f1e6db
